#!/usr/bin/env ansible-playbook

##############################################################
# Author: Gholamreza Sabery Tabrizy
# Email: reza_sabery_89@yahoo.com
# Project Repository: https://github.com/ghrst/Kamailio-HA
##############################################################

- name: This play is going to configure Corosync and Pacemaker
  hosts: kamailioDbCreator
  become: False
  vars_files:
    - settings.yml
  tasks:
    - name: Install sipsak (kamailio's OCF script needs this)
      apt:
        update_cache: yes
        name: sipsak
    
    #FIXME:: Carrying these operation on one of the nodes if enough. Applying settings on multiple nodes causes an error. Anyway it works.
    - name: Now we disable stonith (On a real cluster you must have this)
      shell: crm configure property stonith-enabled=false
      
    - name: Configure no-qourum-policy = ignore because we have a two node cluster.
      shell: crm configure property no-quorum-policy=ignore
      
    - name: For ensuring time-based actions refer to http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html/Pacemaker_Explained/s-rules-recheck.html
      shell: crm configure property cluster-recheck-interval=5m
    
    - name: We want the resources to stick to the node they are on so set default-resource-stickiness = 10000 (This can also be configured per resource)
      shell: crm configure property default-resource-stickiness=10000    

    - name: Copying cib file
      template:
        src: templates/cib.txt
        dest: "{{cibPath}}"
        force: yes
    
    - name: Loading configurations from cib.txt
      shell: crm configure load update {{cibPath}}cib.txt