#!/usr/bin/env ansible-playbook

##############################################################
# Author: Gholamreza Sabery Tabrizy
# Email: reza_sabery_89@yahoo.com
# Project Repository: https://github.com/ghrst/Kamailio-HA
##############################################################

- name: Install and configure Kamailio
  hosts: kamailio
  become: True
  vars_files:
      - settings.yml      
  tasks:  
    - name: Installing compilation prerequisites
      apt:
        update_cache: yes
        name:
          - gcc
          - bison
          - flex
          - make
          - openssl
          - default-libmysqlclient-dev
          - libxmlrpc-core-c3-dev
          - python-mysqldb
          - python-pip
          - mysql-client
    
    - name: Installing a local instance of RTPProxy
      apt: pkg=rtpproxy update_cache=yes
      when: not withRTPProxyCluster
    
    - name: Copy rtpproxy's default file to /etc/default/rtpproxy
      template: src=./templates/rtpproxy.default dest=/etc/default/rtpproxy force=yes
      when: not withRTPProxyCluster
    
    - name: Copy rtpproxy's init script to /etc/init.d/rtpproxy
      copy: src=./files/rtpproxy.init dest=/etc/init.d/rtpproxy force=yes
      notify: restart rtpproxy
      when: not withRTPProxyCluster
      
    - name: Create a directory to store Kamailio's source files
      file: path={{kamailioSrcPath}} state=directory
      
    - name: download Kamailio 4.1.1
      get_url: url={{kamailioSourceUrl}} dest={{kamailioSrcPath}}
      
    - name: Un-taring Kamailio's source file using tar xf
      unarchive: src={{kamailioSrcPath}}/kamailio-4.1.1_src.tar.gz dest={{kamailioSrcPath}} copy=no
      
    - name: Compiling Kamailio
      shell: make prefix=/ all include_modules="db_mysql" chdir={{kamailioSrcPath}}/kamailio-4.1.1/
      
    - name: Installing Kamailio
      shell: make prefix=/ install include_modules="db_mysql" chdir={{kamailioSrcPath}}/kamailio-4.1.1/
      
    - name: Creating group for kamailio
      group: name=kamailio
    
    - name: Creating user for kamailio
      user: name=kamailio home={{kamailioHomeDir}} group=kamailio
      
    - name: Creating /var/run/kamailio and setting premissions
      file: path={{kamailioHomeDir}} owner=kamailio group=kamailio state=directory
      
    - name: Installing Kamailio's Config file in /etc/kamailio/kamailio.cfg
      template: src=./templates/kamailio.cfg dest=/etc/kamailio/kamailio.cfg force=yes
      
    - name: Installing Kamailio's default file to /etc/default/kamailio
      copy: src=./files/kamailio.default dest=/etc/default/kamailio force=yes
    
    - name: Installing Kamailio's init script from files into /etc/init.d/kamailio
      copy: src=./files/kamailio.init dest=/etc/init.d/kamailio mode=0755
        
  handlers:
    - name: restart rtpproxy
      service: name=rtpproxy state=restarted

      
- name: This play creates Kamailio's database
  hosts: kamailioDbCreator
  vars_files:
    - settings.yml
  tasks:
    - name: Copying kamctlrc files
      template: src=templates/kamctlrc dest=/etc/kamailio/kamctlrc force=yes
      
    - name: Installing pexpect >= 3.3
      pip: name=https://pypi.python.org/packages/source/p/pexpect/pexpect-4.0.1.tar.gz
      
    - name: Running kamdbctl create
      expect: 
        command: kamdbctl create
        responses: 
            password: "{{mySqlRootPass}}"
            Install: "y"
  
  
    