#!/usr/bin/env ansible-playbook

##############################################################
# Author: Gholamreza Sabery Tabrizy
# Email: reza_sabery_89@yahoo.com
# Project Repository: https://github.com/ghrst/Kamailio-HA
##############################################################

- name: This play installs and configures MySQL Server for Kamailio. 
  hosts: mysql
  become: False
  vars_files:
    - settings.yml
  tasks:
    - name: Installing mysql-server
      apt: pkg={{ item }} update_cache=yes
      with_items:
         - mysql-server
         - python-mysqldb
    
    - name: Update mysql root password
      mysql_user: 
        name: root
        host: "{{ item }}"
        password: "{{mySqlRootPass}}"
        login_user: root
        login_password: "{{mySqlRootPass}}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - "{{kam1IP}}"
        - "{{kam2IP}}"
        - "{{mySqlHost}}"
        - localhost
        
    - name: Adding Kamailio's database user
      mysql_user:
        name: "{{mySqlKamailioUser}}"
        host: "{{item}}"
        priv: "kamailio.*:ALL,GRANT"
        password: "{{mySqlKamailioPass}}"
        login_user: root
        login_password: "{{mySqlRootPass}}"
      with_items: 
        - 127.0.0.1
        - "{{kamailioPublicIP}}"
        - "{{kam1IP}}"
        - "{{kam2IP}}"
        - localhost
        
    - name: Adding RTPProxy database user
      mysql_user:
        name: "{{rtpProxyMySQLUser}}"
        host: "{{item}}"
        priv: "rtpproxy.*:ALL,GRANT"
        password: "{{rtpProxyMySQLPass}}"
        login_user: root
        login_password: "{{mySqlRootPass}}"
      with_items: 
        - 127.0.0.1
        - "{{kamailioPublicIP}}"
        - "{{kam1IP}}"
        - "{{kam2IP}}"
        - localhost
        
    - name: Ensure MySQL will listen to mySqlBindIP
      lineinfile: dest=/etc/mysql/my.cnf regexp='bind-address\s*=\s*127\.0\.0\.1\s*' line='bind-address   = {{mySqlBindIP}}' state=present backrefs=yes
  
    - name: Restarting MySQL
      service: name=mysql state=restarted
         
        
