#Mysql Settings
mysqlLoginUser: root
mySqlRootPass: password
mySqlKamailioUser: kamailiouser
mySqlKamailioPass: password
mySqlHost: "172.16.0.3"
mySqlBindIP: "{{mySqlHost}}"

#Allowed IP addresses to be connected to remote MySQL server
#FIXME:: These IP addresses should be inferred automatically. Anyway creating Kamailio's DB using two hosts will cause problems.
kam1IP: "172.16.0.4"
kam2IP: "172.16.0.5"


#Kamailio-related settings
kamailioSrcPath: /usr/local/src/kamailio
kamailioHomeDir: /var/run/kamailio
kamailioDbURL: mysql://{{mySqlKamailioUser}}:{{mySqlKamailioPass}}@{{mySqlHost}}/kamailio
#In order to install Kamailio 5xx just change the URL to point to source of 5xx version
kamailioSourceUrl: http://www.kamailio.org/pub/kamailio/4.1.1/src/kamailio-4.1.1_src.tar.gz
kamailioVirtualIP: "172.16.0.7"
kamailioVirtualIPNetMask: "255.255.255.0"
kamailioVirtualIPBroadCast: "172.16.0.255"
kamailioPublicIP: "172.16.0.7"
kamailioSIPDomain: "{{kamailioPublicIP}}"


#Other
preferencesPath: /etc/apt/preferences.d/
mtCastAddr: "239.0.0.95"

#RTPProxy related settings
# If you want to deploy with a cluster of rtpproxy servers set this variable to True and set rtpproxy server informations using rtpServers array.
# Otherwise each node in the cluster will have it's own local rtpproxy server.
withRTPProxyCluster: False  
#This is an array that contains a list of entries that will automatically added to rtpproxy's database
#Each item must be of the form ip:port.
rtpHostsInfo: 
    - 192.168.120.55:7722
    
#If you want to put your RTPProxy servers behind a NAT you should enable withAdvertiseAddr and provide public IP of each private addresses
withAdvertiseAddr: False
advertiseAddresses:
    "192.168.120.55": 185.8.173.33

rtpProxyMySQLUser: rtpproxy
rtpProxyMySQLPass: password    
rtpProxyDBURL: mysql://{{rtpProxyMySQLUser}}:{{rtpProxyMySQLPass}}@{{mySqlHost}}/rtpproxy


#CIB
cibPath: "/usr/local/src/"
